name: Energy Hub
version: "1.3.0"
slug: energy_hub
description: Local home energy management for PowMr PI30MAX and Home Assistant
url: https://github.com/serhiykravchenko-sys/EnergyHub

arch:
  - aarch64

startup: services
boot: auto
init: false

hassio_api: false
homeassistant_api: false
host_network: false

uart: true
udev: true

options:
  powmr_enabled: true
  mqtt_host: core-mosquitto
  mqtt_port: 1883
  mqtt_user: null
  mqtt_password: null
  serial_port: /dev/serial/by-id/REPLACE_WITH_YOUR_FTDI_DEVICE_ID
  protocol: PI30MAX
  command: QPIGS
  poll_interval: 10
  device_name: PowMr 10.2M

schema:
  powmr_enabled: bool
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: password
  serial_port: str
  protocol: str
  command: str
  poll_interval: int
  device_name: str
